USE [master]
GO

/****** Object:  Database [AdventureWorksDW2008]    Script Date: 19-11-2016 11:25:09 ******/
CREATE DATABASE [AdventureWorksDW2008]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AdventureWorksDW2008_Data', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\AdventureWorksDW2008_Data.mdf' , SIZE = 88960KB , MAXSIZE = UNLIMITED, FILEGROWTH = 16384KB )
 LOG ON 
( NAME = N'AdventureWorksDW2008_Log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\AdventureWorksDW2008_Log.LDF' , SIZE = 18432KB , MAXSIZE = 2048GB , FILEGROWTH = 16384KB )
GO

ALTER DATABASE [AdventureWorksDW2008] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AdventureWorksDW2008].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AdventureWorksDW2008] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AdventureWorksDW2008] SET ANSI_NULLS ON 
GO

ALTER DATABASE [AdventureWorksDW2008] SET ANSI_PADDING ON 
GO

ALTER DATABASE [AdventureWorksDW2008] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [AdventureWorksDW2008] SET ARITHABORT ON 
GO

ALTER DATABASE [AdventureWorksDW2008] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AdventureWorksDW2008] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AdventureWorksDW2008] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AdventureWorksDW2008] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AdventureWorksDW2008] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AdventureWorksDW2008] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [AdventureWorksDW2008] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AdventureWorksDW2008] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [AdventureWorksDW2008] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AdventureWorksDW2008] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AdventureWorksDW2008] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AdventureWorksDW2008] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AdventureWorksDW2008] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AdventureWorksDW2008] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [AdventureWorksDW2008] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AdventureWorksDW2008] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AdventureWorksDW2008] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AdventureWorksDW2008] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AdventureWorksDW2008] SET  MULTI_USER 
GO

ALTER DATABASE [AdventureWorksDW2008] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AdventureWorksDW2008] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AdventureWorksDW2008] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AdventureWorksDW2008] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AdventureWorksDW2008] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AdventureWorksDW2008] SET QUERY_STORE = OFF
GO

USE [AdventureWorksDW2008]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [AdventureWorksDW2008] SET  READ_WRITE 
GO

